"use client";

import Link from "next/link";
import Image from "next/image";
import { useEffect, useMemo, useState, type ChangeEvent, type FormEvent } from "react";
import { BadgeCheck, Building2, Check, ChevronRight, CirclePlus, Clock3, ImagePlus, MessageCircle, PackageCheck, Pencil, Power, Settings2, Store, Trash2, UserRound, Wallet, X } from "lucide-react";
import { ProtectedRoute } from "@/components/protected-route";
import { useAuth } from "@/lib/auth-context";
import { createId, formatMoney, kosmateRepository } from "@/lib/local-repository";
import { useLocalData } from "@/lib/use-local-data";
import type { FoodMenuItem, KostListing, KostPhoto, OrderStatus, PartnerKind, ServiceOrder } from "@/lib/models";

const amenitiesList = ["WiFi", "AC", "Kamar mandi dalam", "Kamar mandi luar", "Dapur", "Parkir motor", "Parkir mobil", "CCTV", "Laundry", "Lemari", "Kasur", "Meja belajar", "Listrik termasuk", "Air termasuk"];
const rulesList = ["Tidak diperbolehkan membawa hewan peliharaan", "Dilarang merokok di dalam kamar", "Tamu wajib melapor", "Jam bertamu berlaku", "Menjaga kebersihan", "Tidak membuat keributan"];
const nextStatuses: Partial<Record<OrderStatus, OrderStatus>> = { received: "accepted", accepted: "ready_for_delivery", ready_for_delivery: "on_the_way", in_progress: "ready_for_delivery", on_the_way: "completed" };
const roleLabels: Record<PartnerKind, string> = { kost_owner: "Pemilik Kost", food_merchant: "Mitra Makanan", errand_provider: "Jasa Suruh" };
const photoKinds: KostPhoto["category"][] = ["Kamar", "Kamar mandi", "Bagian luar", "Fasilitas", "Area bersama"];

function DashboardShell({ title, tabs, active, onTab, children }: { title: string; tabs: { id: string; label: string; icon: typeof UserRound }[]; active: string; onTab: (id: string) => void; children: React.ReactNode }) {
  const { user } = useAuth();
  const [data] = useLocalData();
  const partner = user?.role === "customer" || user?.role === "support" ? undefined : user?.role;
  const account = data.accounts.find((item) => item.id === user?.id);
  const provider = data.serviceProviders.find((item) => item.id === account?.partnerId);
  return <section className="page-wrap py-7 sm:py-10"><div className="mb-7 flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-widest text-emerald-700">{roleLabels[partner as PartnerKind]} KosMate</p><h1 className="mt-2 text-3xl font-black tracking-tight text-slate-950">{title}, {user?.name.split(" ")[0]}</h1><p className="mt-2 text-sm text-slate-500">Kelola aktivitas kemitraanmu dari satu tempat.</p></div>{provider && <span className={`inline-flex items-center gap-2 rounded-full px-3 py-2 text-xs font-bold ${provider.verified ? "bg-emerald-50 text-emerald-800" : "bg-amber-50 text-amber-800"}`}>{provider.verified ? <BadgeCheck size={15} /> : <Clock3 size={15} />}{provider.verified ? "Terverifikasi" : "Menunggu verifikasi mock"}</span>}</div><div className="grid gap-5 lg:grid-cols-[230px_minmax(0,1fr)]"><nav className="flex gap-2 overflow-x-auto rounded-2xl border border-slate-100 bg-white p-2 shadow-card lg:flex-col lg:self-start">{tabs.map(({ id, label, icon: Icon }) => <button key={id} onClick={() => onTab(id)} className={`flex shrink-0 items-center gap-3 rounded-xl px-4 py-3 text-left text-sm font-semibold transition ${active === id ? "bg-emerald-700 text-white" : "text-slate-600 hover:bg-emerald-50"}`}><Icon size={17} />{label}</button>)}</nav><div className="min-w-0 rounded-3xl border border-slate-100 bg-white p-5 shadow-card sm:p-7">{children}</div></div><p className="mt-5 text-center text-xs text-slate-400">Prototype lokal · Perubahan tersimpan di browser ini</p></section>;
}

function AccountProfilePanel({title}:{title:string}){const{user}=useAuth();const[data,setData]=useLocalData();const account=data.accounts.find((item)=>item.id===user?.id);const[name,setName]=useState(account?.name??"");const[phone,setPhone]=useState(account?.phone??"");const[saved,setSaved]=useState(false);useEffect(()=>{setName(account?.name??"");setPhone(account?.phone??"");},[account?.name,account?.phone]);function save(event:FormEvent<HTMLFormElement>){event.preventDefault();setData(kosmateRepository.update((current)=>({...current,accounts:current.accounts.map((item)=>item.id===user?.id?{...item,name:name.trim(),phone:phone.trim()}:item),partners:current.partners.map((partner)=>partner.userId===user?.id?{...partner,displayName:name.trim()}:partner),foodMerchants:current.foodMerchants.map((store)=>store.userId===user?.id?{...store,name:name.trim()}:store),serviceProviders:current.serviceProviders.map((provider)=>provider.userId===user?.id?{...provider,name:name.trim(),phone:phone.trim()}:provider)})));setSaved(true);}return <><h2 className="text-xl font-extrabold">{title}</h2><p className="mt-1 text-sm text-slate-500">Kelola informasi akun kemitraanmu.</p><form onSubmit={save} className="mt-5 grid max-w-xl gap-4"><label className="form-label">Nama<input className="form-input" required value={name} onChange={(e)=>setName(e.target.value)}/></label><label className="form-label">Email<input className="form-input" disabled value={account?.email??""}/></label><label className="form-label">Nomor telepon<input className="form-input" value={phone} onChange={(e)=>setPhone(e.target.value)}/></label>{saved&&<p className="text-sm text-emerald-700">Profil tersimpan di browser ini.</p>}<button className="button-primary w-fit">Simpan Profil</button></form></>;}

function OwnerDashboard() {
  const { user } = useAuth(); const [data, setData] = useLocalData();
  const [tab, setTab] = useState("profile"); const [formOpen, setFormOpen] = useState(false); const [editingSlug, setEditingSlug] = useState<string | null>(null); const [statusText, setStatusText] = useState("");
  const [name, setName] = useState(""); const [type, setType] = useState("Putri"); const [price, setPrice] = useState(""); const [address, setAddress] = useState(""); const [area, setArea] = useState(""); const [roomCount, setRoomCount] = useState("1"); const [amenities, setAmenities] = useState<string[]>([]); const [description, setDescription] = useState(""); const [rules, setRules] = useState<string[]>([]); const [customRule, setCustomRule] = useState(""); const [roomName, setRoomName] = useState("Kamar Standard"); const [roomSize, setRoomSize] = useState(""); const [roomPrice, setRoomPrice] = useState(""); const [roomAmenities, setRoomAmenities] = useState(""); const [availability, setAvailability] = useState("1"); const [latitude, setLatitude] = useState(""); const [longitude, setLongitude] = useState(""); const [photos, setPhotos] = useState<KostPhoto[]>([]); const [photoCategory, setPhotoCategory] = useState<KostPhoto["category"]>("Kamar");
  const kosts = useMemo(() => data.kosts.filter((kost) => kost.ownerId === user?.id), [data.kosts, user?.id]);
  const ownerConversations = data.conversations.filter((conversation) => conversation.kind === "kost_owner" && conversation.participantId === user?.id);
  const requests = data.kostRequests.filter((request) => kosts.some((kost) => kost.slug === request.kostSlug));

  function resetForm(kost?: KostListing) {
    setEditingSlug(kost?.slug ?? null); setName(kost?.name ?? ""); setType(kost?.tags[0] ?? "Putri"); setPrice(kost ? String(kost.price) : ""); setAddress(kost?.address ?? kost?.location ?? ""); setArea(kost?.area ?? ""); setRoomCount(String(kost?.roomCount ?? 1)); setAmenities(kost?.amenities ?? kost?.facilities ?? []); setDescription(kost?.description ?? ""); setRules(kost?.rules ?? []); setCustomRule(""); const room = kost?.roomTypes?.[0]; setRoomName(room?.name ?? "Kamar Standard"); setRoomSize(room?.size ?? ""); setRoomPrice(String(room?.price ?? kost?.price ?? "")); setRoomAmenities(room?.facilities.join(", ") ?? ""); setAvailability(String(room?.availability ?? 1)); setLatitude(kost?.mockCoordinate?.latitude?.toString() ?? ""); setLongitude(kost?.mockCoordinate?.longitude?.toString() ?? ""); setPhotos(kost?.photos ?? []); setFormOpen(true); setStatusText("");
  }
  function toggle(setter: (next: string[]) => void, values: string[], value: string) { setter(values.includes(value) ? values.filter((item) => item !== value) : [...values, value]); }
  function addPhotos(event: ChangeEvent<HTMLInputElement>) {
    const selected = Array.from(event.target.files ?? []);
    if (photos.length + selected.length > 5) { setStatusText("Maksimal 5 foto untuk mock listing ini."); event.target.value = ""; return; }
    if (selected.some((file) => file.size > 600 * 1024)) { setStatusText("Setiap foto maksimal 600 KB agar muat di penyimpanan lokal."); event.target.value = ""; return; }
    Promise.all(selected.map((file) => new Promise<KostPhoto>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => typeof reader.result === "string" ? resolve({ id: createId("photo"), url: reader.result, name: file.name, category: photoCategory, isPrimary: false }) : reject(); reader.readAsDataURL(file); }))).then((newPhotos) => setPhotos((previous) => previous.length ? [...previous, ...newPhotos] : newPhotos.map((photo, index) => ({ ...photo, isPrimary: index === 0 })))).catch(() => setStatusText("Foto tidak dapat dibaca."));
    event.target.value = "";
  }
  function saveKost(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (!photos.length) { setStatusText("Tambahkan minimal satu foto kost sebelum menyimpan listing."); return; } const finalRules = [...rules, ...(customRule.trim() ? [customRule.trim()] : [])]; const previous = data.kosts.find((item) => item.slug === editingSlug); const slug = editingSlug ?? `${name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "")}-${Date.now().toString().slice(-5)}`; const mainPhoto = photos.find((photo) => photo.isPrimary) ?? photos[0];
    const nextKost: KostListing = { slug, name: name.trim(), location: address.trim(), address: address.trim(), area: area.trim(), price: Number(price), rating: previous?.rating ?? 0, reviews: previous?.reviews ?? 0, image: mainPhoto?.url ?? previous?.image ?? data.kosts[0]?.image ?? "", tags: [type, area.trim()], facilities: amenities, amenities, description: description.trim(), verified: previous?.verified ?? false, ownerId: user!.id, active: previous?.active ?? true, roomCount: Number(roomCount), photos: photos.map((photo) => ({ ...photo, isPrimary: photo.id === mainPhoto?.id })), rules: finalRules, mockCoordinate: { latitude: latitude ? Number(latitude) : null, longitude: longitude ? Number(longitude) : null, isMock: true }, roomTypes: [{ id: previous?.roomTypes?.[0]?.id ?? createId("room"), name: roomName.trim(), size: roomSize.trim(), price: Number(roomPrice || price), facilities: roomAmenities.split(",").map((item) => item.trim()).filter(Boolean), availability: Number(availability) }] };
    const next = kosmateRepository.update((current) => ({ ...current, kosts: previous ? current.kosts.map((item) => item.slug === slug ? nextKost : item) : [...current.kosts, nextKost] })); setData(next); setFormOpen(false); setStatusText("Data kost tersimpan.");
  }
  function deactivate(slug: string) { setData(kosmateRepository.update((current) => ({ ...current, kosts: current.kosts.map((kost) => kost.slug === slug ? { ...kost, active: false } : kost) }))); }
  const tabs = [{ id: "profile", label: "Profil", icon: UserRound }, { id: "kost", label: "Kost Saya", icon: Building2 }, { id: "messages", label: "Chat / Pesan", icon: MessageCircle }, { id: "requests", label: "Permintaan / Booking", icon: PackageCheck }, { id: "reviews", label: "Ulasan", icon: Check }, { id: "settings", label: "Pengaturan", icon: Settings2 }];
  return <DashboardShell title="Halo" tabs={tabs} active={tab} onTab={setTab}>
    {tab === "profile" && <AccountProfilePanel title="Profil Pemilik Kost"/>}
    {tab === "kost" && <><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-xl font-extrabold">Kost Saya</h2><p className="mt-1 text-sm text-slate-500">Listingmu tampil pada pencarian kost customer.</p></div><button onClick={() => resetForm()} className="button-primary"><CirclePlus size={16} /> Tambah Kost</button></div>{statusText && <p className="mt-4 text-sm text-emerald-700">{statusText}</p>}
      {formOpen && <form onSubmit={saveKost} className="mt-5 grid gap-5 rounded-2xl bg-slate-50 p-4 sm:p-5">
        <div className="flex items-start justify-between gap-3"><div><h3 className="font-extrabold">{editingSlug ? "Edit Kost" : "Informasi Kost"}</h3><p className="mt-1 text-xs text-slate-500">Isi informasi yang akan dilihat calon penghuni.</p></div><button type="button" onClick={() => setFormOpen(false)} className="icon-button" aria-label="Tutup form"><X size={18} /></button></div>
        <section><h4 className="form-label">Foto Kost</h4><div className="grid gap-3 sm:grid-cols-[180px_1fr]"><select className="form-input" value={photoCategory} onChange={(e) => setPhotoCategory(e.target.value as KostPhoto["category"])}>{photoKinds.map((kind) => <option key={kind}>{kind}</option>)}</select><label className="form-control cursor-pointer"><ImagePlus size={18} /><input type="file" accept="image/*" multiple onChange={addPhotos} /><span>Pilih beberapa foto · maksimal 5 foto</span></label></div><div className="mt-3 grid grid-cols-2 gap-3 sm:grid-cols-3">{photos.map((photo) => <article key={photo.id} className="overflow-hidden rounded-xl border border-slate-200 bg-white"><div className="relative h-28 bg-slate-100"><Image src={photo.url} alt={photo.name} fill unoptimized sizes="200px" className="object-cover" /></div><div className="flex flex-wrap items-center justify-between gap-2 p-2"><span className="truncate text-[11px] text-slate-500">{photo.category}</span><div className="flex gap-1"><button type="button" className={`rounded-lg p-1 text-xs ${photo.isPrimary ? "bg-emerald-100 text-emerald-800" : "bg-slate-100 text-slate-600"}`} onClick={() => setPhotos((list) => list.map((item) => ({ ...item, isPrimary: item.id === photo.id })))} title="Pilih foto utama"><Check size={14} /></button><button type="button" className="rounded-lg bg-rose-50 p-1 text-rose-700" onClick={() => setPhotos((list) => { const remaining = list.filter((item) => item.id !== photo.id); if (!remaining.some((item) => item.isPrimary) && remaining[0]) remaining[0].isPrimary = true; return [...remaining]; })} aria-label="Hapus foto"><Trash2 size={14} /></button></div></div>{photo.isPrimary && <p className="px-2 pb-2 text-[10px] font-bold text-emerald-700">Foto utama</p>}</article>)}</div></section>
        <section className="grid gap-3 sm:grid-cols-2"><h4 className="font-bold sm:col-span-2">Informasi Dasar Kost</h4><label className="form-label">Nama kost<input className="form-input" required value={name} onChange={(e) => setName(e.target.value)} /></label><label className="form-label">Tipe kost<select className="form-input" value={type} onChange={(e) => setType(e.target.value)}><option>Putra</option><option>Putri</option><option>Campur</option></select></label><label className="form-label">Harga sewa per bulan<input className="form-input" required min="0" type="number" value={price} onChange={(e) => { setPrice(e.target.value); if (!roomPrice) setRoomPrice(e.target.value); }} /></label><label className="form-label">Jumlah kamar<input className="form-input" min="1" type="number" value={roomCount} onChange={(e) => setRoomCount(e.target.value)} /></label><label className="form-label sm:col-span-2">Alamat lengkap<input className="form-input" required value={address} onChange={(e) => setAddress(e.target.value)} placeholder="Jalan, nomor, kelurahan, kota" /></label><label className="form-label">Area / patokan<input className="form-input" required value={area} onChange={(e) => setArea(e.target.value)} placeholder="Contoh: Dekat kampus (area mock)" /></label><div className="grid grid-cols-2 gap-2"><label className="form-label">Latitude mock<input className="form-input" type="number" step="any" value={latitude} onChange={(e) => setLatitude(e.target.value)} placeholder="Opsional" /></label><label className="form-label">Longitude mock<input className="form-input" type="number" step="any" value={longitude} onChange={(e) => setLongitude(e.target.value)} placeholder="Opsional" /></label></div></section>
        <section><h4 className="font-bold">Fasilitas Kost</h4><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-3">{amenitiesList.map((item) => <label key={item} className="flex items-center gap-2 rounded-xl border border-slate-200 bg-white p-2.5 text-xs text-slate-700"><input type="checkbox" checked={amenities.includes(item)} onChange={() => toggle(setAmenities, amenities, item)} className="accent-emerald-700" />{item}</label>)}</div></section>
        <label className="form-label">Deskripsi Kost<textarea className="form-input" required rows={4} value={description} onChange={(e) => setDescription(e.target.value)} placeholder="Ceritakan tentang kost, lingkungan sekitar, akses, dan keunggulan kost..." /></label>
        <section><h4 className="font-bold">Aturan Kost</h4><div className="mt-3 grid gap-2 sm:grid-cols-2">{rulesList.map((rule) => <label key={rule} className="flex items-center gap-2 rounded-xl border border-slate-200 bg-white p-2.5 text-xs text-slate-700"><input type="checkbox" checked={rules.includes(rule)} onChange={() => toggle(setRules, rules, rule)} className="accent-emerald-700" />{rule}</label>)}</div><label className="form-label mt-3">Aturan lainnya<input className="form-input" value={customRule} onChange={(e) => setCustomRule(e.target.value)} placeholder="Jam bertamu atau aturan khusus" /></label></section>
        <section className="grid gap-3 rounded-xl border border-slate-200 bg-white p-4 sm:grid-cols-2"><h4 className="font-bold sm:col-span-2">Detail Tipe Kamar</h4><label className="form-label">Nama tipe kamar<input className="form-input" value={roomName} onChange={(e) => setRoomName(e.target.value)} /></label><label className="form-label">Luas kamar<input className="form-input" value={roomSize} onChange={(e) => setRoomSize(e.target.value)} placeholder="Contoh: 3 × 4 m" /></label><label className="form-label">Harga tipe kamar<input className="form-input" min="0" type="number" value={roomPrice} onChange={(e) => setRoomPrice(e.target.value)} /></label><label className="form-label">Ketersediaan kamar<input className="form-input" min="0" type="number" value={availability} onChange={(e) => setAvailability(e.target.value)} /></label><label className="form-label sm:col-span-2">Fasilitas kamar<input className="form-input" value={roomAmenities} onChange={(e) => setRoomAmenities(e.target.value)} placeholder="Pisahkan dengan koma: kasur, lemari, meja" /></label></section>
        <div className="flex flex-wrap gap-2"><button className="button-primary">Simpan Kost</button><button type="button" onClick={() => setFormOpen(false)} className="button-secondary">Batal</button></div>
      </form>}
      <div className="mt-5 grid gap-3">{kosts.map((kost) => <article key={kost.slug} className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-slate-100 p-4"><div><div className="flex items-center gap-2"><h3 className="font-bold">{kost.name}</h3><span className="rounded-full bg-emerald-50 px-2 py-1 text-[10px] font-bold text-emerald-800">{kost.active === false ? "Nonaktif" : "Aktif"}</span></div><p className="mt-1 text-xs text-slate-500">{kost.area} · {formatMoney(kost.price)}/bulan · {kost.photos?.length ?? 0} foto</p><Link href={`/kost/${kost.slug}`} className="mt-2 inline-flex text-xs font-bold text-emerald-800">Lihat halaman customer <ChevronRight size={14} /></Link></div><div className="flex gap-2"><button className="button-secondary !px-3 !py-2" onClick={() => resetForm(kost)} aria-label="Edit kost"><Pencil size={15} /></button>{kost.active !== false && <button className="button-secondary !px-3 !py-2" onClick={() => deactivate(kost.slug)} aria-label="Nonaktifkan kost"><Power size={15} /></button>}</div></article>)}{!kosts.length && <div className="rounded-2xl border border-dashed border-slate-200 p-9 text-center text-sm text-slate-500">Belum ada listing. Tambahkan kost untuk mulai tampil di pencarian.</div>}</div></>}
    {tab === "messages" && <><h2 className="text-xl font-extrabold">Chat / Pesan</h2><p className="mt-1 text-sm text-slate-500">Percakapan customer yang menghubungi kostmu.</p><div className="mt-5 grid gap-3">{ownerConversations.map((conversation) => <Link key={conversation.id} href={`/pesan?conversation=${conversation.id}`} className="rounded-2xl border border-slate-100 p-4 hover:bg-emerald-50/50"><p className="font-bold">{data.kosts.find((kost) => kost.slug === conversation.kostSlug)?.name ?? "Kost"}</p><p className="mt-1 text-xs text-slate-500">Buka chat customer <ChevronRight className="inline" size={13} /></p></Link>)}{!ownerConversations.length && <p className="rounded-2xl bg-slate-50 p-5 text-sm text-slate-500">Belum ada pesan.</p>}</div></>}
    {tab === "requests" && <><h2 className="text-xl font-extrabold">Permintaan / Booking</h2><div className="mt-5 grid gap-3">{requests.map((request) => { const conversation = ownerConversations.find((item) => item.kostSlug === request.kostSlug && item.customerId === request.customerId); return <article key={request.id} className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-slate-100 p-4"><div><p className="font-bold">{data.accounts.find((account) => account.id === request.customerId)?.name ?? "Customer"}</p><p className="mt-1 text-xs text-slate-500">{data.kosts.find((kost) => kost.slug === request.kostSlug)?.name} · {request.status}</p></div>{conversation && <Link href={`/pesan?conversation=${conversation.id}`} className="button-secondary">Balas <MessageCircle size={15} /></Link>}</article>})}{!requests.length && <p className="rounded-2xl bg-slate-50 p-5 text-sm text-slate-500">Belum ada permintaan booking.</p>}</div></>}
    {tab === "reviews" && <><h2 className="text-xl font-extrabold">Ulasan</h2><p className="mt-2 text-sm text-slate-500">Ringkasan ulasan untuk kost yang kamu kelola.</p><div className="mt-5 grid gap-3">{kosts.map((kost) => <article key={kost.slug} className="rounded-2xl bg-slate-50 p-4"><p className="font-bold">{kost.name}</p><p className="mt-1 text-sm text-amber-600">★ {kost.rating} · {kost.reviews} ulasan mock</p></article>)}{!kosts.length && <p className="text-sm text-slate-500">Ulasan muncul setelah listing mendapatkan review.</p>}</div></>}
    {tab === "settings" && <><h2 className="text-xl font-extrabold">Pengaturan</h2><p className="mt-2 text-sm text-slate-500">Pengaturan notifikasi dan informasi profil pemilik kost.</p><div className="mt-5 rounded-2xl bg-slate-50 p-4 text-sm">Notifikasi permintaan booking <span className="float-right font-bold text-emerald-800">Aktif (mock)</span></div><Link href="/mitra/login" className="mt-5 inline-flex text-sm font-bold text-emerald-800">Ganti akun</Link></>}
  </DashboardShell>;
}

function MerchantDashboard() {
  const { user } = useAuth(); const [data, setData] = useLocalData(); const [tab, setTab] = useState("profile"); const [itemName, setItemName] = useState(""); const [itemDescription, setItemDescription] = useState(""); const [itemPrice, setItemPrice] = useState(""); const [menuImage, setMenuImage] = useState(""); const [editingItem, setEditingItem] = useState<string | null>(null); const [statusText, setStatusText] = useState("");
  const merchant = data.foodMerchants.find((item) => item.userId === user?.id || item.id === data.accounts.find((account) => account.id === user?.id)?.partnerId);
  const menu = data.foodMenuItems.filter((item) => item.merchantId === merchant?.id); const orders = data.orders.filter((item) => item.merchantId === merchant?.id).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));
  function readPhoto(file:File,setter:(data:string)=>void){if(file.size>600*1024){setStatusText("Foto maksimal 600 KB untuk penyimpanan lokal.");return;}const reader=new FileReader();reader.onload=()=>setter(typeof reader.result==="string"?reader.result:"");reader.readAsDataURL(file);}
  function saveItem(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!merchant) return; const id = editingItem ?? createId("menu"); const item: FoodMenuItem = { id, merchantId: merchant.id, name: itemName.trim(), description: itemDescription.trim(), image: menuImage || data.foodMenuItems.find((food)=>food.id===editingItem)?.image || "https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=700&q=80", price: Number(itemPrice), available: true }; const next = kosmateRepository.update((current) => ({ ...current, foodMenuItems: editingItem ? current.foodMenuItems.map((food) => food.id === id ? item : food) : [...current.foodMenuItems, item], foodMerchants: current.foodMerchants.map((store) => store.id === merchant.id ? { ...store, menuItemIds: editingItem ? store.menuItemIds : [...store.menuItemIds, id] } : store) })); setData(next); setEditingItem(null); setItemName(""); setItemDescription(""); setItemPrice(""); setMenuImage(""); }
  function updateOrder(orderId: string, status: OrderStatus) { setData(kosmateRepository.update((current) => ({ ...current, orders: current.orders.map((order) => order.id === orderId ? { ...order, status, updatedAt: new Date().toISOString() } : order) }))); }
  const tabs = [{id:"profile",label:"Profil",icon:UserRound},{id:"store",label:"Toko",icon:Store},{id:"menu",label:"Menu",icon:CirclePlus},{id:"orders",label:"Pesanan",icon:PackageCheck},{id:"revenue",label:"Pendapatan",icon:Wallet},{id:"reviews",label:"Ulasan",icon:Check},{id:"settings",label:"Pengaturan",icon:Settings2}];
  return <DashboardShell title="Halo" tabs={tabs} active={tab} onTab={setTab}>
    {tab === "profile" && <><AccountProfilePanel title="Profil Mitra Makanan"/><p className="mt-4 rounded-2xl bg-emerald-50 p-4 text-sm">Profil toko: {merchant?.name ?? user?.name}</p></>}
    {tab === "store" && <><h2 className="text-xl font-extrabold">Toko</h2><p className="mt-2 text-sm text-slate-500">Informasi toko yang tampil dalam pilihan merchant.</p><div className="mt-5 grid max-w-xl gap-3"><label className="form-label">Nama toko<input className="form-input" value={merchant?.name ?? ""} onChange={(e) => { if (!merchant) return; setData(kosmateRepository.update((current) => ({ ...current, foodMerchants: current.foodMerchants.map((store) => store.id === merchant.id ? { ...store, name: e.target.value } : store) }))); }} /></label><label className="form-label">Foto toko (mock/local)<span className="form-control"><ImagePlus size={16}/><input type="file" accept="image/*" onChange={(e)=>{const file=e.target.files?.[0];if(!file||!merchant)return;readPhoto(file,(image)=>setData(kosmateRepository.update((current)=>({...current,foodMerchants:current.foodMerchants.map((store)=>store.id===merchant.id?{...store,photo:image}:store)}))));}}/></span></label><label className="form-label">Lokasi toko (mock)<input className="form-input" value={merchant?.location ?? ""} onChange={(e) => { if (!merchant) return; setData(kosmateRepository.update((current) => ({ ...current, foodMerchants: current.foodMerchants.map((store) => store.id === merchant.id ? { ...store, location: e.target.value } : store) }))); }} /></label><label className="form-label">Estimasi persiapan<input className="form-input" value={merchant?.estimate ?? ""} onChange={(e) => { if (!merchant) return; setData(kosmateRepository.update((current) => ({ ...current, foodMerchants: current.foodMerchants.map((store) => store.id === merchant.id ? { ...store, estimate: e.target.value } : store) }))); }} /></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={merchant?.available ?? false} onChange={(e) => { if (!merchant) return; setData(kosmateRepository.update((current) => ({ ...current, foodMerchants: current.foodMerchants.map((store) => store.id === merchant.id ? { ...store, available: e.target.checked } : store) }))); }} />Toko sedang tersedia</label><p className="text-xs text-emerald-700">Perubahan profil toko tersimpan otomatis di mock data lokal.</p></div></>}
    {tab === "menu" && <><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-extrabold">Menu</h2><p className="mt-1 text-sm text-slate-500">Kelola makanan dan minuman yang dapat dipesan.</p></div><button onClick={() => { setEditingItem(null); setItemName(""); setItemDescription(""); setItemPrice(""); setMenuImage(""); setStatusText("Form menu baru siap."); }} className="button-primary"><CirclePlus size={16} /> Tambah Menu</button></div>{statusText && <p className="mt-3 text-sm text-emerald-700">{statusText}</p>}<form onSubmit={saveItem} className="mt-4 grid gap-3 rounded-2xl bg-slate-50 p-4 sm:grid-cols-2"><h3 className="font-bold sm:col-span-2">{editingItem ? "Edit menu" : "Menu baru"}</h3><label className="form-label">Nama makanan<input required className="form-input" value={itemName} onChange={(e)=>setItemName(e.target.value)} /></label><label className="form-label">Harga<input required type="number" min="0" className="form-input" value={itemPrice} onChange={(e)=>setItemPrice(e.target.value)} /></label><label className="form-label sm:col-span-2">Foto menu (opsional)<span className="form-control"><ImagePlus size={16}/><input type="file" accept="image/*" onChange={(e)=>{const file=e.target.files?.[0];if(file)readPhoto(file,setMenuImage);}}/></span></label><label className="form-label sm:col-span-2">Deskripsi singkat<textarea className="form-input" value={itemDescription} onChange={(e)=>setItemDescription(e.target.value)} /></label><button className="button-primary sm:col-span-2">Simpan Menu</button></form><div className="mt-5 grid gap-3">{menu.map((item)=><article key={item.id} className="flex items-center justify-between gap-3 rounded-2xl border border-slate-100 p-4"><div><p className="font-bold">{item.name}</p><p className="text-xs text-slate-500">{item.description} · {formatMoney(item.price)}</p></div><div className="flex gap-2"><button className="button-secondary !px-3 !py-2" onClick={()=>{setEditingItem(item.id);setItemName(item.name);setItemDescription(item.description);setItemPrice(String(item.price));setMenuImage(item.image);}} aria-label="Edit menu"><Pencil size={14}/></button><button className="button-secondary !px-3 !py-2" onClick={()=>setData(kosmateRepository.update((current)=>({...current,foodMenuItems:current.foodMenuItems.filter((food)=>food.id!==item.id),foodMerchants:current.foodMerchants.map((store)=>store.id===merchant?.id?{...store,menuItemIds:store.menuItemIds.filter((id)=>id!==item.id)}:store)})))} aria-label="Hapus menu"><Trash2 size={14}/></button></div></article>)}</div></>}
    {tab === "orders" && <OrdersForPartner orders={orders} data={data} onAdvance={updateOrder} />}
    {tab === "revenue" && <RevenuePanel orders={orders} />}
    {tab === "reviews" && <><h2 className="text-xl font-extrabold">Ulasan</h2><p className="mt-2 text-sm text-slate-500">Rating toko: ★ {merchant?.rating ?? 0} · ulasan mock</p></>}
    {tab === "settings" && <><h2 className="text-xl font-extrabold">Pengaturan</h2><p className="mt-2 text-sm text-slate-500">Pengaturan toko dan notifikasi pesanan mock.</p></>}
  </DashboardShell>;
}

function OrdersForPartner({ orders, data, onAdvance }: { orders: ServiceOrder[]; data: ReturnType<typeof useLocalData>[0]; onAdvance: (orderId: string, status: OrderStatus) => void }) {
  return <><h2 className="text-xl font-extrabold">Pesanan</h2><div className="mt-5 grid gap-3">{orders.map((order) => { const next = nextStatuses[order.status]; return <article key={order.id} className="rounded-2xl border border-slate-100 p-4"><p className="text-xs text-slate-400">{order.id.slice(-8).toUpperCase()}</p><h3 className="mt-1 font-bold">{data.services.find((service)=>service.id===order.serviceId)?.name ?? "Pesanan"}</h3>{order.pickupLocation&&<p className="mt-1 text-sm text-slate-500">Pickup: {order.pickupLocation}</p>}<p className="mt-1 text-sm text-slate-500">Delivery: {order.deliveryLocation ?? order.address ?? "Alamat belum diisi"}</p><p className="mt-2 font-bold text-emerald-800">{formatMoney(order.totalAmount)}</p><div className="mt-3 flex flex-wrap gap-2">{next&&<button onClick={()=>onAdvance(order.id,next)} className="button-secondary">Tandai {next.replaceAll("_"," ")}</button>}{order.conversationId&&<Link href={`/pesan?conversation=${order.conversationId}`} className="button-secondary"><MessageCircle size={15}/>Buka chat</Link>}</div></article>})}{!orders.length&&<p className="rounded-xl bg-slate-50 p-5 text-sm text-slate-500">Belum ada pesanan.</p>}</div></>;
}
function RevenuePanel({ orders }: { orders: ServiceOrder[] }) { const revenue = orders.filter((order)=>order.status==="completed").reduce((sum,order)=>sum+(order.totalAmount??0),0); return <><h2 className="text-xl font-extrabold">Pendapatan</h2><p className="mt-2 text-sm text-slate-500">Ringkasan lokal dari order yang selesai.</p><p className="mt-4 text-3xl font-black text-emerald-800">{formatMoney(revenue)}</p><p className="text-xs text-slate-400">{orders.filter((order)=>order.status==="completed").length} order selesai · mock</p></>; }

function ErrandDashboard() {
  const { user } = useAuth(); const [data, setData] = useLocalData(); const [tab, setTab] = useState("profile"); const [counter, setCounter] = useState<Record<string,string>>({}); const [extraFeeInput,setExtraFeeInput]=useState<Record<string,string>>({});
  const account = data.accounts.find((item)=>item.id===user?.id); const providerId = account?.partnerId;
  const orders = data.orders.filter((order)=>(order.providerId===providerId || (account?.role==="errand_provider"&&order.details.fulfillmentType==="JASA_SURUH") || order.status==="awaiting_quote" || order.status==="awaiting_approval")).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));
  function offer(order: ServiceOrder) {
    const amount = Number(counter[order.id]);
    if (!amount || amount < 0) return;
    const now = new Date().toISOString();
    const extras = Number(extraFeeInput[order.id] ?? order.otherFees) || 0;
    const quote = { id: createId("quote"), orderId: order.id, createdBy: user!.id, itemsAmount: order.itemsAmount, shippingFee: order.shippingFee, serviceFee: amount, otherFees: extras, totalAmount: order.itemsAmount + order.shippingFee + amount + extras, status: "sent" as const, createdAt: now, updatedAt: now };
    const negotiation = { id: createId("negotiation"), orderId: order.id, authorId: user!.id, amount, status: "proposed" as const, createdAt: now };
    setData(kosmateRepository.update((current) => ({ ...current, orders: current.orders.map((item) => item.id === order.id ? { ...item, providerId, providerOffer: amount, serviceFee: amount, otherFees: extras, totalAmount: quote.totalAmount, pricingMode: "negotiable", pricingStatus: "countered", paymentStatus: "not_started", status: "awaiting_approval", updatedAt: now } : item), quotes: [...current.quotes.map((item) => item.orderId === order.id && item.status === "sent" ? { ...item, status: "superseded" as const, updatedAt: now } : item), quote], negotiations: [...current.negotiations, negotiation] })));
  }
  function accept(order: ServiceOrder) {
    const now = new Date().toISOString();
    const amount = order.customerOffer ?? order.providerOffer ?? 0;
    const extras = Number(extraFeeInput[order.id] ?? order.otherFees) || 0;
    setData(kosmateRepository.update((current) => ({ ...current, orders: current.orders.map((item) => item.id === order.id ? { ...item, providerId, providerOffer: order.providerOffer ?? amount, serviceFee: amount, otherFees: extras, totalAmount: item.itemsAmount + item.shippingFee + amount + extras, pricingMode: "negotiable", pricingStatus: "accepted", paymentStatus: "unpaid_mock", status: "accepted", updatedAt: now } : item), negotiations: [...current.negotiations.map((item) => item.orderId === order.id && item.status === "proposed" ? { ...item, status: "accepted" as const } : item), { id: createId("negotiation"), orderId: order.id, authorId: user!.id, amount, status: "accepted" as const, createdAt: now }] })));
  }
  function advance(id:string,status:OrderStatus){setData(kosmateRepository.update((current)=>({...current,orders:current.orders.map((item)=>item.id===id?{...item,status,updatedAt:new Date().toISOString()}:item)})));}
  const tabs=[{id:"profile",label:"Profil",icon:UserRound},{id:"incoming",label:"Permintaan masuk",icon:PackageCheck},{id:"orders",label:"Pesanan",icon:CirclePlus},{id:"revenue",label:"Pendapatan",icon:Wallet},{id:"rating",label:"Rating",icon:Check},{id:"settings",label:"Pengaturan",icon:Settings2}];
  return <DashboardShell title="Halo" tabs={tabs} active={tab} onTab={setTab}>
    {tab==="profile"&&<><AccountProfilePanel title="Profil Jasa Suruh"/><p className="mt-4 rounded-2xl bg-emerald-50 p-4 text-sm">Profil area dan ketersediaan dikelola secara mock. Lokasi peta belum digunakan.</p></>}
    {tab==="incoming"&&<><h2 className="text-xl font-extrabold">Permintaan Masuk</h2><div className="mt-5 grid gap-3">{orders.filter((order)=>order.status==="awaiting_quote"||order.status==="awaiting_approval").map((order)=>{const service=data.services.find((item)=>item.id===order.serviceId);return <article key={order.id} className="rounded-2xl border border-slate-100 p-4"><div className="flex flex-wrap justify-between gap-3"><div><p className="text-xs text-slate-400">{service?.name} · {order.id.slice(-8)}</p><p className="mt-1 whitespace-pre-wrap text-sm">{order.details.request??order.details.foodName??"Permintaan layanan"}</p><p className="mt-2 text-xs text-slate-500">Pickup: {order.pickupLocation||"—"} · Delivery: {order.deliveryLocation||order.address||"—"}</p>{order.customerOffer&&<p className="mt-2 text-sm font-bold text-emerald-800">Penawaran fee customer: {formatMoney(order.customerOffer)}</p>}{order.conversationId&&<Link href={`/pesan?conversation=${order.conversationId}`} className="mt-2 inline-flex items-center gap-1 text-xs font-bold text-emerald-800">Buka chat <MessageCircle size={13}/></Link>}</div><span className="h-fit rounded-full bg-amber-50 px-3 py-1 text-xs font-bold text-amber-800">{order.status==="awaiting_quote"?"Butuh penawaran":"Menunggu persetujuan"}</span></div><div className="mt-4 flex flex-wrap gap-2">{order.customerOffer&&<button onClick={()=>accept(order)} className="button-primary">Terima penawaran</button>}<input className="form-input !w-40" type="number" min="0" placeholder="Fee jasa baru" value={counter[order.id]??""} onChange={(e)=>setCounter((all)=>({...all,[order.id]:e.target.value}))}/><input className="form-input !w-40" type="number" min="0" placeholder="Harga barang / biaya lain" value={extraFeeInput[order.id]??""} onChange={(e)=>setExtraFeeInput((all)=>({...all,[order.id]:e.target.value}))}/><button onClick={()=>offer(order)} className="button-secondary">Kirim penawaran</button></div></article>})}{!orders.some((order)=>order.status==="awaiting_quote"||order.status==="awaiting_approval")&&<p className="rounded-xl bg-slate-50 p-5 text-sm text-slate-500">Belum ada permintaan yang menunggu penawaran.</p>}</div></>}
    {tab==="orders"&&<OrdersForPartner orders={orders.filter((order)=>!["awaiting_quote","awaiting_approval"].includes(order.status))} data={data} onAdvance={advance}/>}
    {tab==="revenue"&&<RevenuePanel orders={orders}/>}
    {tab==="rating"&&<><h2 className="text-xl font-extrabold">Rating</h2><p className="mt-3 text-2xl font-black text-amber-500">★ 4,8</p><p className="text-sm text-slate-500">Rating mitra mock</p></>}
    {tab==="settings"&&<><h2 className="text-xl font-extrabold">Pengaturan</h2><p className="mt-2 text-sm text-slate-500">Atur notifikasi dan ketersediaan jasa mock.</p></>}
  </DashboardShell>;
}

export function PartnerDashboard() {
  const { user } = useAuth();
  const content = user?.role === "kost_owner" ? <OwnerDashboard /> : user?.role === "food_merchant" ? <MerchantDashboard /> : <ErrandDashboard />;
  return <ProtectedRoute role="partner">{content}</ProtectedRoute>;
}
