"use client";

import Image from "next/image";
import Link from "next/link";
import { useMemo, useState } from "react";
import { ArrowRight, Check, Clock3, MessageCircle, PackageCheck, ReceiptText, X } from "lucide-react";
import { ProtectedRoute } from "@/components/protected-route";
import { useAuth } from "@/lib/auth-context";
import { createId, formatMoney, kosmateRepository } from "@/lib/local-repository";
import { useLocalData } from "@/lib/use-local-data";
import type { OrderStatus, ServiceOrder } from "@/lib/models";

const statusLabels: Record<OrderStatus, string> = { received:"Menunggu Diproses",accepted:"Sedang Diproses",in_progress:"Sedang Dikerjakan",ready_for_delivery:"Siap Diantar",on_the_way:"Dalam perjalanan",completed:"Selesai",cancelled:"Pesanan dibatalkan",awaiting_quote:"Menunggu penawaran mitra",awaiting_approval:"Menunggu persetujuan kamu" };
function CustomerOrders(){
 const {user}=useAuth();const [data,setData]=useLocalData();const [counter,setCounter]=useState<Record<string,string>>({});const orders=useMemo(()=>data.orders.filter((order)=>order.customerId===user?.id).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)),[data.orders,user?.id]);const openConversations=useMemo(()=>data.conversations.filter((conversation)=>conversation.customerId===user?.id&&!["approved","closed"].includes(conversation.status)).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)),[data.conversations,user?.id]);const steps=["received","accepted","ready_for_delivery","on_the_way","completed"] as const;
 function answer(order:ServiceOrder,accept:boolean){const now=new Date().toISOString();if(accept){const amount=order.providerOffer??order.customerOffer??0;const total=order.itemsAmount+order.shippingFee+amount+order.otherFees;setData(kosmateRepository.update((current)=>({...current,orders:current.orders.map((item)=>item.id===order.id?{...item,status:"accepted",pricingStatus:"accepted",providerOffer:order.providerOffer??amount,serviceFee:amount,totalAmount:total,paymentStatus:"unpaid_mock",updatedAt:now}:item),quotes:current.quotes.map((item)=>item.orderId===order.id&&item.status==="sent"?{...item,status:"accepted",updatedAt:now}:item),negotiations:current.negotiations.map((item)=>item.orderId===order.id&&item.status==="proposed"?{...item,status:"accepted"}:item)})));}else{setData(kosmateRepository.update((current)=>({...current,orders:current.orders.map((item)=>item.id===order.id?{...item,status:"awaiting_quote",pricingStatus:"rejected",paymentStatus:"not_started",updatedAt:now}:item),quotes:current.quotes.map((item)=>item.orderId===order.id&&item.status==="sent"?{...item,status:"rejected",updatedAt:now}:item),negotiations:current.negotiations.map((item)=>item.orderId===order.id&&item.status==="proposed"?{...item,status:"rejected"}:item)})));}}
 function counterOffer(order:ServiceOrder){const amount=Number(counter[order.id]);if(!amount)return;const now=new Date().toISOString();const negotiation={id:createId("negotiation"),orderId:order.id,authorId:user!.id,amount,status:"proposed" as const,createdAt:now};setData(kosmateRepository.update((current)=>({...current,orders:current.orders.map((item)=>item.id===order.id?{...item,status:"awaiting_quote",pricingStatus:"waiting_provider",customerOffer:amount,serviceFee:amount,providerOffer:undefined,totalAmount:null,paymentStatus:"not_started",updatedAt:now}:item),quotes:current.quotes.map((item)=>item.orderId===order.id&&item.status==="sent"?{...item,status:"superseded",updatedAt:now}:item),negotiations:[...current.negotiations,negotiation]})));setCounter((all)=>({...all,[order.id]:""}));}
 return <section className="page-wrap py-8 sm:py-12"><p className="text-xs font-bold uppercase tracking-widest text-emerald-700">Customer</p><div className="mt-2 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-black tracking-tight text-slate-950">Pesanan Saya</h1><p className="mt-2 text-sm text-slate-500">Pantau order, quotation, dan rincian permintaanmu.</p></div><div className="flex gap-2"><Link href="/pesan" className="button-secondary"><MessageCircle size={16}/>Pesan</Link><Link href="/layanan" className="button-primary"><PackageCheck size={16}/>Cari layanan</Link></div></div>
 {openConversations.length>0&&<div className="mt-7 grid gap-3">{openConversations.map((conversation)=>{const service=data.services.find((item)=>item.id===conversation.serviceId);return <article key={conversation.id} className="flex flex-wrap items-center justify-between gap-4 rounded-2xl border border-emerald-100 bg-emerald-50/60 p-4"><div><p className="text-xs font-bold uppercase tracking-wider text-emerald-800">{conversation.kind==="support"?"Chat CS KosMate":"Chat berlangsung"}</p><h2 className="mt-1 font-bold">{service?.name??(conversation.kind==="kost_owner"?data.kosts.find((kost)=>kost.slug===conversation.kostSlug)?.name:"Percakapan")}</h2><p className="mt-1 text-sm text-slate-600">{conversation.status==="quoted"?`Quotation ${formatMoney(conversation.quotedAmount)} menunggu jawabanmu.`:"Lanjutkan percakapan."}</p></div><Link href={`/pesan?conversation=${conversation.id}`} className="button-primary">Buka chat <ArrowRight size={15}/></Link></article>})}</div>}
 {!orders.length?<div className="mt-8 rounded-3xl border border-dashed border-slate-200 bg-white px-5 py-16 text-center"><span className="mx-auto grid size-12 place-items-center rounded-full bg-emerald-50 text-emerald-700"><ReceiptText size={21}/></span><h2 className="mt-4 font-bold">Belum ada pesanan</h2><p className="mt-1 text-sm text-slate-500">Mock order yang kamu buat akan muncul di sini.</p><Link href="/layanan" className="button-primary mt-5">Jelajahi layanan <ArrowRight size={15}/></Link></div>:<div className="mt-7 grid gap-4">{orders.map((order)=>{const service=data.services.find((item)=>item.id===order.serviceId);const merchant=data.foodMerchants.find((item)=>item.id===order.merchantId);const provider=data.serviceProviders.find((item)=>item.id===order.providerId);const items=data.orderItems.filter((item)=>item.orderId===order.id);const conversation=data.conversations.find((item)=>item.id===order.conversationId);const index=steps.indexOf(order.status as typeof steps[number]);const priced=order.pricingStatus==="countered"||order.pricingStatus==="quoted";return <article key={order.id} className="rounded-3xl border border-slate-100 bg-white p-5 shadow-card sm:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-semibold text-slate-400">Order {order.id.slice(-8).toUpperCase()} · {new Date(order.createdAt).toLocaleString("id-ID",{dateStyle:"medium",timeStyle:"short"})}</p><h2 className="mt-2 text-lg font-extrabold">{service?.name??"Layanan KosMate"}</h2><p className="mt-1 text-sm text-slate-500">{merchant?.name??provider?.name??(order.pricingMode==="customer_offer"||order.pricingMode==="provider_quote"?"Permintaan jasa": "KosMate")}</p></div><span className={`rounded-full px-3 py-1.5 text-xs font-bold ${order.status==="completed"?"bg-emerald-50 text-emerald-800":order.status==="cancelled"?"bg-rose-50 text-rose-700":"bg-amber-50 text-amber-800"}`}>{statusLabels[order.status]}</span></div>
 {items.length>0&&<div className="mt-4 grid gap-2 border-t border-slate-100 pt-4">{items.map((item)=><div key={item.id} className="flex items-center justify-between gap-3 text-sm"><span className="flex items-center gap-2 text-slate-600">{item.image&&<span className="relative size-10 overflow-hidden rounded-lg"> <Image src={item.image} alt={item.name} fill unoptimized sizes="40px" className="object-cover"/></span>}{item.name} × {item.quantity}</span><span className="font-semibold">{item.unitAmount===null?"Menunggu harga":formatMoney(item.unitAmount*item.quantity)}</span></div>)}</div>}
 {order.details.request&&<p className="mt-3 whitespace-pre-line rounded-xl bg-slate-50 p-3 text-sm leading-5 text-slate-600">{order.details.request}</p>}{order.details.foodName&&<p className="mt-2 text-sm text-slate-600">{order.details.foodName} · {order.details.shopName} · {order.details.quantity} pcs</p>}
 {order.details.attachmentDataUrl&&<figure className="mt-4"><Image src={order.details.attachmentDataUrl} alt={order.details.attachmentName??"Foto kebutuhan"} width={800} height={600} unoptimized className="max-h-64 rounded-xl border border-slate-200 object-contain"/><figcaption className="mt-1 text-xs text-slate-500">{order.details.attachmentName}</figcaption></figure>}
 {(order.pickupLocation||order.deliveryLocation||order.address||order.scheduledAt)&&<div className="mt-4 grid gap-2 border-t border-slate-100 pt-4 text-sm sm:grid-cols-2">{order.pickupLocation&&<p className="text-slate-600"><strong>Lokasi Pengambilan / Pickup:</strong> {order.pickupLocation}</p>}{(order.deliveryLocation||order.address)&&<p className="text-slate-600"><strong>Alamat Pengantaran / Delivery:</strong> {order.deliveryLocation||order.address}</p>}{order.scheduledAt&&<p className="flex items-center gap-1 text-slate-500"><Clock3 size={14}/>{new Date(order.scheduledAt).toLocaleString("id-ID",{dateStyle:"medium",timeStyle:"short"})}</p>}</div>}
 <div className="mt-4 flex flex-wrap items-center justify-between gap-2 border-t border-slate-100 pt-4"><div className="text-xs text-slate-500"><p>Subtotal {formatMoney(order.itemsAmount)} · ongkir {formatMoney(order.shippingFee)} · biaya layanan {formatMoney(order.serviceFee)} · biaya lain {formatMoney(order.otherFees)}</p><p className="mt-1 text-sm font-bold text-slate-900">Total {formatMoney(order.totalAmount)}</p></div><div className="flex flex-wrap gap-2">{conversation&&<Link href={`/pesan?conversation=${conversation.id}`} className="button-secondary"><MessageCircle size={15}/>Buka chat</Link>}{order.totalAmount!==null&&order.pricingStatus==="accepted"&&order.paymentStatus==="unpaid_mock"&&<Link href={`/pembayaran?orderId=${order.id}`} className="button-primary">Lanjut ke Pembayaran</Link>}{order.paymentStatus==="paid_mock"&&<span className="rounded-xl bg-emerald-50 px-3 py-2 text-xs font-bold text-emerald-800">Pembayaran mock diterima</span>}</div></div>
 {priced&&order.status!=="cancelled"&&<div className="mt-4 rounded-2xl border border-emerald-100 bg-emerald-50 p-4"><p className="text-sm font-bold">{order.pricingStatus==="countered"?"Mitra mengajukan harga":"Harga diajukan"}</p><p className="mt-1 text-xl font-black text-emerald-800">{formatMoney(order.providerOffer)}</p><p className="mt-1 text-xs text-slate-600">Harga barang {formatMoney(order.itemsAmount)} · fee jasa {formatMoney(order.providerOffer)} · biaya lain {formatMoney(order.otherFees)} · total {formatMoney(order.itemsAmount+(order.providerOffer??0)+order.otherFees)}</p><div className="mt-3 flex flex-wrap gap-2"><button onClick={()=>answer(order,true)} className="button-primary"><Check size={15}/>Terima harga</button><button onClick={()=>answer(order,false)} className="button-secondary"><X size={15}/>Tolak</button><div className="flex gap-2"><input className="form-input !w-40" type="number" min="1" placeholder="Ajukan harga lain" value={counter[order.id]??""} onChange={(e)=>setCounter((all)=>({...all,[order.id]:e.target.value}))}/><button onClick={()=>counterOffer(order)} className="button-secondary">Kirim penawaran</button></div></div></div>}
 {order.pricingStatus==="waiting_provider"&&<p className="mt-3 rounded-xl bg-amber-50 p-3 text-sm text-amber-800">{order.customerOffer?`Penawaran fee ${formatMoney(order.customerOffer)} menunggu jawaban mitra.`:"Permintaan menunggu quotation dari mitra."}</p>}
 {index>=0&&<div className="mt-5 grid grid-cols-2 gap-2 border-t border-slate-100 pt-4 sm:grid-cols-5">{steps.map((step,stepIndex)=><div key={step} className={`flex items-center gap-2 text-[10px] font-semibold sm:flex-col sm:items-start sm:text-xs ${stepIndex<=index?"text-emerald-800":"text-slate-300"}`}><span className={`grid size-6 shrink-0 place-items-center rounded-full ${stepIndex<=index?"bg-emerald-700 text-white":"bg-slate-100"}`}>{stepIndex<index?<Check size={13}/>:stepIndex+1}</span>{statusLabels[step]}</div>)}</div>}
 </article>})}</div>}
 </section>;
}
export default function OrdersPage(){return <ProtectedRoute role="customer"><CustomerOrders/></ProtectedRoute>;}
