"use client";

import Image from "next/image";
import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import { useState } from "react";
import { ArrowLeft, BadgeCheck, BedDouble, Check, Clock3, MapPin, MessageCircle, ShieldCheck, Star } from "lucide-react";
import { formatRupiah } from "@/lib/data";
import { MapPreview } from "@/components/map-preview";
import { KostSaveButton } from "@/components/kost-save-button";
import { useAuth } from "@/lib/auth-context";
import { createId, kosmateRepository } from "@/lib/local-repository";
import { useLocalData } from "@/lib/use-local-data";
import type { RoomType } from "@/lib/models";

export default function KostDetailPage() {
  const { slug } = useParams<{ slug: string }>(); const router = useRouter(); const { user } = useAuth(); const [data] = useLocalData(); const [selectedPhoto, setSelectedPhoto] = useState<string | null>(null);
  const kost = data.kosts.find((item) => item.slug === slug && item.active !== false); const photos = kost?.photos?.length ? kost.photos : kost ? [{ id: `${kost.slug}-main`, url: kost.image, name: kost.name, category: "Kamar" as const, isPrimary: true }] : []; const mainPhoto = photos.find((photo) => photo.isPrimary) ?? photos[0]; const shownPhoto = photos.find((photo) => photo.id === selectedPhoto) ?? mainPhoto;
  const owner = kost?.ownerId ? data.accounts.find((account) => account.id === kost.ownerId) : undefined;
  function contactOwner() {
    if (!user || user.role !== "customer") { router.push(`/login?next=${encodeURIComponent(`/kost/${slug}`)}`); return; }
    if (!kost) return;
    const participantId = owner?.id ?? `mock-owner-${kost.slug}`; const existing = data.conversations.find((conversation) => conversation.kind === "kost_owner" && conversation.customerId === user.id && conversation.kostSlug === kost.slug && conversation.status !== "closed");
    if (existing) { router.push(`/pesan?conversation=${existing.id}`); return; }
    const now = new Date().toISOString(); const conversationId = createId("conversation"); const conversation = { id: conversationId, kind: "kost_owner" as const, customerId: user.id, participantId, kostSlug: kost.slug, status: "consulting" as const, createdAt: now, updatedAt: now };
    const messages = [{ id: createId("message"), conversationId, senderId: user.id, senderRole: "customer" as const, body: `Halo, saya tertarik dengan ${kost.name}. Apakah kamar masih tersedia?`, createdAt: now }, { id: createId("message"), conversationId, senderId: participantId, senderRole: "support" as const, body: "Terima kasih sudah menghubungi pemilik. Pesanmu sudah diterima (simulasi chat KosMate).", createdAt: now }];
    kosmateRepository.update((current) => ({ ...current, conversations: [...current.conversations, conversation], messages: [...current.messages, ...messages], kostRequests: [...current.kostRequests, { id: createId("kost-request"), kostSlug: kost.slug, customerId: user.id, status: "new", createdAt: now }] }));
    router.push(`/pesan?conversation=${conversationId}`);
  }
  if (!kost) return <section className="page-wrap py-16 text-center"><h1 className="text-2xl font-bold text-slate-900">Kost tidak ditemukan atau sudah tidak aktif.</h1><Link href="/kost" className="button-primary mt-5">Kembali ke pencarian</Link></section>;
  const mapPoint = { id: kost.slug, label: kost.name, latitude: kost.mockCoordinate?.latitude ?? -6.9, longitude: kost.mockCoordinate?.longitude ?? 107.61, address: kost.address ?? kost.location, isMock: true as const };
  return <section className="page-wrap py-6 sm:py-10">
    <Link href="/kost" className="mb-5 inline-flex items-center gap-2 text-sm font-semibold text-slate-500 hover:text-emerald-800"><ArrowLeft size={17} /> Kembali ke hasil pencarian</Link>
    <div className="grid gap-3 overflow-hidden rounded-3xl sm:grid-cols-[1.5fr_1fr] sm:grid-rows-2 sm:gap-3"><button onClick={() => setSelectedPhoto(mainPhoto?.id ?? null)} className="relative min-h-[260px] overflow-hidden rounded-2xl text-left sm:row-span-2 sm:min-h-[420px]">{shownPhoto && <Image src={shownPhoto.url} alt={shownPhoto.name || `Foto ${kost.name}`} fill priority unoptimized sizes="(max-width: 640px) 100vw, 60vw" className="object-cover" />}<span className="absolute bottom-3 left-3 rounded-lg bg-slate-950/65 px-3 py-2 text-xs font-semibold text-white">{shownPhoto?.category ?? "Foto utama"}</span></button>{photos.filter((photo) => photo.id !== mainPhoto?.id).slice(0, 2).map((photo) => <button key={photo.id} onClick={() => setSelectedPhoto(photo.id)} className="relative min-h-[130px] overflow-hidden rounded-2xl text-left sm:min-h-[205px]"><Image src={photo.url} alt={photo.name} fill unoptimized sizes="(max-width: 640px) 50vw, 40vw" className="object-cover" /><span className="absolute bottom-2 left-2 rounded-lg bg-slate-950/65 px-2.5 py-1.5 text-[10px] font-semibold text-white">{photo.category}</span></button>)}</div>
    {photos.length > 1 && <div className="mt-3 flex gap-2 overflow-x-auto">{photos.map((photo) => <button key={photo.id} onClick={() => setSelectedPhoto(photo.id)} aria-label={`Lihat foto ${photo.category}`} className={`relative size-16 shrink-0 overflow-hidden rounded-xl border-2 ${shownPhoto?.id === photo.id ? "border-emerald-600" : "border-transparent"}`}><Image src={photo.url} alt={photo.name} fill unoptimized sizes="64px" className="object-cover" /></button>)}</div>}
    <div className="mt-7 grid items-start gap-8 lg:grid-cols-[minmax(0,1fr)_340px]"><div>
      <div className="flex flex-wrap items-start justify-between gap-4"><div>{kost.verified && <span className="inline-flex items-center gap-1 rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-bold text-emerald-800"><BadgeCheck size={14} /> Terverifikasi</span>}<h1 className="mt-3 text-3xl font-black tracking-tight text-slate-950 sm:text-4xl">{kost.name}</h1><div className="mt-2 flex flex-wrap items-center gap-x-4 gap-y-2 text-sm text-slate-500"><span className="flex items-center gap-1 font-semibold text-slate-800"><Star size={16} fill="#f5ad32" className="text-amber-400" />{kost.rating} <span className="font-normal text-slate-400">({kost.reviews} ulasan)</span></span><span className="flex items-center gap-1"><MapPin size={15} />{kost.address ?? kost.location}</span></div></div><KostSaveButton /></div>
      <div className="mt-7 flex flex-wrap items-center gap-2 border-y border-slate-100 py-4">{(kost.amenities ?? kost.facilities).map((item) => <span key={item} className="facility-chip"><Check size={15} />{item}</span>)}</div>
      <section className="py-7"><h2 className="text-xl font-extrabold text-slate-900">Deskripsi Kost</h2><p className="mt-3 max-w-3xl whitespace-pre-line text-sm leading-7 text-slate-600">{kost.description}</p><p className="mt-3 flex items-center gap-2 text-sm text-slate-500"><MapPin size={15} />{kost.area}{kost.mockCoordinate?.isMock && <span className="rounded-full bg-slate-100 px-2 py-1 text-[10px]">Lokasi mock</span>}</p></section>
      <section className="border-t border-slate-100 py-7"><h2 className="text-xl font-extrabold text-slate-900">Fasilitas</h2><div className="mt-5 grid gap-3 sm:grid-cols-2">{(kost.amenities ?? kost.facilities).map((facility) => <span key={facility} className="flex items-center gap-2.5 text-sm text-slate-700"><span className="grid size-6 place-items-center rounded-full bg-emerald-50 text-emerald-700"><Check size={14} /></span>{facility}</span>)}</div></section>
      {!!kost.rules?.length && <section className="border-t border-slate-100 py-7"><h2 className="text-xl font-extrabold">Aturan Kost</h2><ul className="mt-4 grid gap-2 sm:grid-cols-2">{kost.rules.map((rule) => <li key={rule} className="flex gap-2 text-sm text-slate-600"><Check className="mt-0.5 shrink-0 text-emerald-700" size={15}/>{rule}</li>)}</ul></section>}
      {!!kost.roomTypes?.length && <section className="border-t border-slate-100 py-7"><h2 className="text-xl font-extrabold">Detail Kamar</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{kost.roomTypes.map((room: RoomType) => <article key={room.id} className="rounded-2xl border border-slate-100 p-4"><div className="flex items-start justify-between gap-2"><div><h3 className="font-bold">{room.name}</h3><p className="mt-1 flex items-center gap-1 text-xs text-slate-500"><BedDouble size={14}/>{room.size || "Ukuran belum diisi"}</p></div><span className="text-sm font-extrabold text-emerald-800">{formatRupiah(room.price)}/bln</span></div><p className="mt-2 text-xs text-slate-500">Tersedia {room.availability} kamar</p>{room.facilities.length>0&&<p className="mt-2 text-xs text-slate-600">{room.facilities.join(" · ")}</p>}</article>)}</div></section>}
    </div><aside className="space-y-4 lg:sticky lg:top-24"><div className="rounded-3xl border border-slate-100 bg-white p-5 shadow-card sm:p-6"><p className="text-xs text-slate-500">Harga sewa per bulan</p><p className="mt-1 text-2xl font-black text-emerald-800">{formatRupiah(kost.price)}<span className="text-sm font-medium text-slate-400"> / bulan</span></p><button onClick={contactOwner} className="button-primary mt-5 w-full !py-3.5"><MessageCircle size={17} /> Hubungi Pemilik</button><div className="mt-4 flex items-center gap-3 rounded-2xl bg-emerald-50/70 p-3"><span className="grid size-11 place-items-center rounded-full bg-emerald-100 font-bold text-emerald-800">{owner?.name?.slice(0, 2).toUpperCase() ?? "PM"}</span><div className="min-w-0 flex-1"><p className="text-sm font-bold text-slate-900">{owner?.name ?? "Pemilik Kost"}</p><p className="mt-0.5 flex items-center gap-1 text-xs text-slate-500"><span className="size-1.5 rounded-full bg-emerald-500" /> Chat lewat KosMate</p></div><ShieldCheck size={18} className="text-emerald-700" /></div><p className="mt-4 flex items-center gap-2 text-xs text-slate-500"><Clock3 size={14} /> Respons melalui chat internal</p></div><div className="rounded-3xl border border-slate-100 bg-white p-3 shadow-card"><MapPreview className="min-h-[200px]" points={[mapPoint]} /><div className="px-2 pb-1 pt-3"><p className="font-bold text-slate-900">Lokasi kost</p><p className="mt-1 text-xs leading-5 text-slate-500">{kost.area} · lokasi perkiraan untuk demo, bukan titik alamat terverifikasi</p></div></div></aside></div>
  </section>;
}
